import { MCQ, SubjectName } from '../../../types.js';

/**
 * CTET December 2024 - Paper II
 * Child Development & Pedagogy Questions (Q1-Q30)
 */
export const cdpQuestions: MCQ[] = [
  {
      question: "Which of these statements would advocates of progressive education a gree with ?",
      options: [
        "Children are a distinct life-stage that hold importance because of ‘w hat they would become as adults’ rather than ‘what they are as children’.",
        "Children are naturally ‘good’ and society corrupts them.",
        "Children are naturally ‘uncivilized’ and socialization is necess ary to make them moral human beings.",
        "Children are born in a social, cultural, economic context and this ba ckground influences their development. ª",
      ],
      correctAnswerIndex: 3,
      explanation: "This child development question highlights Children are born in a social, cultural, economic context an. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Changes in emotion, self-perception and interpersonal relationships with families, peers and friends are studied under __________ domain of development.",
      options: [
        "Psycho-social",
        "Physical",
        "Cognitive",
        "Linguistic",
      ],
      correctAnswerIndex: 0,
      explanation: "This child development question highlights Psycho-social domain. Changes in emotion, self-perception and interpersonal relationships are studied under the psycho-social domain of development. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "The behaviours, interests, attitudes, skills and personality traits that a culture considers appropriate for specific gender are referred to as __________ and are __________.",
      options: [
        "Gender identity; genetically determined",
        "Gender roles; culturally defined",
        "Gender roles; genetically determined",
        "Gender identity; culturally defined",
      ],
      correctAnswerIndex: 1,
      explanation: "This child development question highlights Gender identity; culturally defined. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "[Question 4 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "As per Jean Piaget’s theory of Cognitive Development :",
      options: [
        "(1) Previous knowledge doesn’t play any role in the process of learning.",
        "(2) Biological factors such as maturation don’t play any role in c ognitive development.",
        "(3) Learning experiences depend on children’s current level of cognitive fun ctioning.",
        "(4) Memorization should be prioritized over learning through experienc e. ¡",
      ],
      correctAnswerIndex: 2,
      explanation: "According to Jean Piaget's theory of cognitive development, (3) Learning experiences depend on children’s current level . This aligns with Piaget's constructivist approach where children actively construct knowledge through experiences. Piaget emphasized that learning depends on the child's current developmental stage and cognitive maturity, as outlined in NCF 2005's focus on developmentally appropriate pedagogy.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Lev Vygotsky views cognitive development as :",
      options: [
        "(1) effective adoption to the environment process",
        "(2) a collaborative process",
        "(3) an individual activity",
        "(4) a unified process ‹ﬂ ﬂ",
      ],
      correctAnswerIndex: 1,
      explanation: "Lev Vygotsky's sociocultural theory emphasizes (2) a collaborative process. Vygotsky viewed cognitive development as a collaborative process involving social interaction and cultural tools. This perspective, central to NCF 2005, highlights the importance of scaffolding and the Zone of Proximal Development in effective teaching.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "While proposing the relationship between language and thinking process, Lev Vygotsky conceptualized language as a/an :",
      options: [
      "Independent domain which is not related to cognition.",
      "cultural tool which facilitates cognition in multiple ways.",
      "form of egocentric speech used to only fulfill basic needs.",
      "hinderance to the development of cognitive abilities.",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Which of the following is an example of a performance goal orientati on ?",
      options: [
        "A student studies hard to further her own growth.",
        "A student studies hard to achieve a deep understanding of a topic.",
        "A student studies hard to get a good grade and be better than others.",
        "A student studies hard to learn as much as possible from the teacher.",
      ],
      correctAnswerIndex: 2,
      explanation: "This child development question highlights A student studies hard to get a good grade and be better tha. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Following Lev Vygotsky’s ideas, a teacher should :",
      options: [
        "practice reciprocal teaching with her students.",
        "discourage the use of cultural tools by students.",
        "disseminate the knowledge to be memorized by the students.",
        "encourage students to compete with each other. ‹ﬂ ﬂ",
      ],
      correctAnswerIndex: 0,
      explanation: "Lev Vygotsky's sociocultural theory emphasizes practice reciprocal teaching with her students.. Vygotsky viewed cognitive development as a collaborative process involving social interaction and cultural tools. This perspective, central to NCF 2005, highlights the importance of scaffolding and the Zone of Proximal Development in effective teaching.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "[Question 10 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "In which of the following method teacher and student interchange thei r roles ?",
      options: [
        "(1) Reciprocal teaching (2) Conditioned learning",
        "(3) Receptive learning (4) Expository teaching",
        "(1) ¬(2)•",
        "(3) ª˝„(4)ﬂ",
      ],
      correctAnswerIndex: 0,
      explanation: "This child development question highlights (1) Reciprocal teaching (2) Conditioned learning. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "She then multiplied each number by 1 2       − . Identify the correct statement regarding the above situation.",
      options: [
      "Number of terms in the ascending order will change.",
      "Ascending order of numbers will still remain the same.",
      "Mean of the numbers will remain the same.",
      "Ascending order will now be changed to descending order.",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Howard Gardner’s theory of multiple intelligence proposes that :",
      options: [
        "(1) Intelligence can successfully predict academic success.",
        "(2) Intelligences change over time.",
        "(3) Intelligence is primarily inherited.",
        "(4) Intelligence can be measured accurately and predicated precisely. „",
      ],
      correctAnswerIndex: 1,
      explanation: "This child development question highlights (2) Intelligences change over time.. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "While there exists a possibility of intra-group individual differences, yet most students with Autism :",
      options: [
      "perform superior skills of imaginative play.",
      "acquire advanced socio-emotional reciprocity.",
      "demonstrate advanced communication skills.",
      "express strict adherence to routine or steps.",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Assertion (A) :Creating an environment of fear and stress keeps students ‘on their’ toes and facilitates meaningful learning. Reason (R) : Learning is governed only by extrinsic factors. Choose the correct option.",
      options: [
        "(1) Both (A) and (R) are false.",
        "(2) Both (A) and (R) are true and (R) is the correct explanation of (A).",
        "(3) Both (A) and (R) are true but (R) is not the correct explanation of (A).",
        "(4) (A) is true but (R) is false. •(A) : (R) : •",
      ],
      correctAnswerIndex: 0,
      explanation: "This child development question highlights (1) Both (A) and (R) are false.. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "[Question 16 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Which of the following statement aptly describes the purpose of a dia gnostic assessment ?",
      options: [
        "(1) To identify the areas where students may need additional support or in struction.",
        "(2) To give students the opportunity to critically assess the work of t heir peers.",
        "(3) To identify the attitude patterns of students and design a career guid ance programme as per their needs.",
        "(4) To provide feedback to the teacher about their teaching methods.",
      ],
      correctAnswerIndex: 0,
      explanation: "This question addresses assessment practices. (1) To identify the areas where students may need additional. Effective assessment should be formative, diagnostic, and learner-centered, focusing on growth rather than mere grading. NCF 2005 advocates for continuous and comprehensive evaluation that supports learning.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Ten year old Kakuli is struggling with a difficult math problem. What can her teacher do to enhance her problem-solving skills ?",
      options: [
      "Give severe punishment so that it is not repeated in future",
      "Give her the solution to the problem",
      "Tell her to skip the problem and move on to the next one",
      "Encourage her to keep trying and offer scaffolding when needed Œ‚",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Jean Piaget perceives __________ to be __________. Lev-Vygotsky believes __________ to be __________.",
      options: [
        "Private speech, effective in self-regulation; egocentric speech, a sign of c ognitive immaturity",
        "Egocentric speech, a sign of cognitive immaturity; private speech, effec tive in self-regulation",
        "Egocentric speech, effective in self-regulation; private speech, a sign of cognitive immaturity",
        "Private speech, a sign of cognitive immaturity; egocentric speech, effect ive in self-regulation",
      ],
      correctAnswerIndex: 1,
      explanation: "According to Jean Piaget's theory of cognitive development, Egocentric speech, a sign of cognitive immaturity; private s. This aligns with Piaget's constructivist approach where children actively construct knowledge through experiences. Piaget emphasized that learning depends on the child's current developmental stage and cognitive maturity, as outlined in NCF 2005's focus on developmentally appropriate pedagogy.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Universal design for learning does NOT involve :",
      options: [
        "(1) Practicing forms of labelling and categorization of learners.",
        "(2) Giving all learners various ways of acquiring information and knowledge.",
        "(3) Providing all learners alternatives for demonstrating what the lear ners know.",
        "(4) Tapping into all learners’ interests and offering challenges accor dingly. •(1)(2)‚(3)(4)‚",
      ],
      correctAnswerIndex: 0,
      explanation: "This child development question highlights (1) Practicing forms of labelling and categorization of lear. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Which of the following statements about Lawrence Kohlberg’s theory is correct ?",
      options: [
      "It takes into account effects of culture and gender on moral reasoning.",
      "It does not specify exact stages for progression of moral development in children.",
      "It is based on the study done through experimental methods.",
      "It presents conflicting situations to children.",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Assertion (A) : Each child finds opportunities to play, experiment and discover thei r world. Reason (R) : Childhood is a universal construct. Choose the correct option.",
      options: [
        "(1) Both (A) and (R) are false.",
        "(2) Both (A) and (R) are true and (R) is the correct explanation of (A).",
        "(3) Both (A) and (R) are true but (R) is not the correct explanation of (A).",
        "(4) (A) is true but (R) is false. •(A) : (R) : ’",
      ],
      correctAnswerIndex: 0,
      explanation: "This child development question highlights (4) (A) is true but (R) is false. •(A) : (R) : ’. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Which of the following is an example of a question that promotes anal ytical thinking ?",
      options: [
        "(1) Who was the leader of Germany during World War II ?",
        "(2) In which year did World War II end ?",
        "(3) Which countries were directly involved in the World War II ?",
        "(4) Which factors contributed to the outbreak of World War II ?",
      ],
      correctAnswerIndex: 3,
      explanation: "This child development question highlights (4) Which factors contributed to the outbreak of World War I. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "While engaging students who are visually challenged, teachers should use __________ which __________.",
      options: [
      "Frequency modulated transmission devices; are an auditory system.",
      "Braille, is a tactile system.",
      "Braille, is an auditory system.",
      "Frequency modulated transmission devices; are a tactile system. ©Ÿ",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "You are a teacher who wants to encourage your students to think criti cally and creatively. Which of the following strategies is most likely to foster this type of thi nking ?",
      options: [
        "Lecturing on the topic and providing students with detailed notes.",
        "Assigning a project in which students must memorize and present inf ormation on a topic.",
        "Providing students with open-ended questions to come up with their o wn solutions.",
        "Giving students multiple-choice tests to assess their knowledge. •",
      ],
      correctAnswerIndex: 2,
      explanation: "This child development question highlights Providing students with open-ended questions to come up with. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Which of the following is an example of assessment for student’s learn ing ?",
      options: [
        "A rubric given to students at the beginning of a project, outlining w hat they need to do to achieve a certain grade.",
        "A final exam that covers all the material learned throughout the term.",
        "A quiz and brainstorming at the beginning of class to check for pr ior knowledge.",
        "A standardized test used to compare students across the country.",
      ],
      correctAnswerIndex: 0,
      explanation: "This question addresses assessment practices. A rubric given to students at the beginning of a project, ou. Effective assessment should be formative, diagnostic, and learner-centered, focusing on growth rather than mere grading. NCF 2005 advocates for continuous and comprehensive evaluation that supports learning.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "[Question 27 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "Assertion (A) : 12-year Amana gets scared every time the teacher asks her to answer or solve t he maths problem on the blackboard because she fears that the teacher will scold her and she would be embarrassed. Reason (R) : When students feel unsafe and anxious their learning is adversely affec ted. Choose the correct option.",
      options: [
        "Providing students with a step-by-step guide on how to complete a task related to the new material.",
        "Lecturing on new material and providing students with a list of key terms to memorize.",
        "Assign students to read the textbook chapter and answer questions at t he end.",
        "Ask students to share their own experiences related to the new material and then connect them to the topic. ",
      ],
      correctAnswerIndex: 1,
      explanation: "This child development question highlights Lecturing on new material and providing students with a list. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "A teacher wants to enable meaningful and analytical learning in her class by providing opportunities for students to connect their prior knowledge to new concepts. Which of the following teaching strategies would be most effective ?",
      options: [
      "Providing students with a step-by-step guide on how to complete a task related to the new material.",
      "Lecturing on new material and providing students with a list of key terms to memorize.",
      "Assign students to read the textbook chapter and answer questions at the end.",
      "Ask students to share their own experiences related to the new material and then connect them to the topic.",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    },
  {
      question: "In an inclusive classroom the teacher :",
      options: [
        "Tries to encourage children to do better by promoting competitive spi rit.",
        "Identifies ‘deficits’ in children and correctly labels them.",
        "Segregates children based on differing academic capabilities.",
        "Modifies the curriculum and pedagogical strategies to suit varied needs of children.  ",
      ],
      correctAnswerIndex: 3,
      explanation: "This child development question highlights Modifies the curriculum and pedagogical strategies to suit v. Understanding these developmental principles is essential for creating inclusive, child-centered classrooms as advocated by NCF 2005. Teachers should recognize individual differences and adapt pedagogy accordingly.",
      subjectName: SubjectName.CDP,
      topicId: "child-development",
      subTopicId: "pedagogy",
      difficulty: "medium",
    }
];
