import { MCQ, SubjectName } from '../../../types.js';

/**
 * CTET December 2024 - Paper II
 * Language II (Hindi) Questions (Q121-Q150)
 * 
 * Paper II Structure:
 * - Q1-30: CDP
 * - Q31-90: Science & Mathematics (60 questions)
 * - Q91-120: Language I (English) - 30 questions
 * - Q121-150: Language II (Hindi) - 30 questions
 */
export const languageIIHindiQuestions: MCQ[] = [
  {
      question: "Read the following statements : (A) Netarhat is located at a height of 3696 feet. (B) It is referred to as the ‘Queen of Chota Nagpur’. (C) Netarhat is blessed with verdant banyan forests.",
      options: [
        "it brings peace and comfort",
        "it makes you breathless",
        "it makes you visit the place year after year",
        "it evokes curiosity",
      ],
      correctAnswerIndex: 0,
      explanation: "This social studies question examines it evokes curiosity. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 122 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "As mentioned in para 1, the quaint hill station, Netarhat gives peace and calm to visitors b ecause :",
      options: [
        "they can go paragliding from hill tops",
        "they can be away from hectic city life",
        "they can go fishing in the lake waters",
        "they can enjoy train rides",
      ],
      correctAnswerIndex: 1,
      explanation: "This social studies question examines they can be away from hectic city life. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Complete the given word analogy : gorgeous : beautiful :: tranquil : ? .",
      options: [
        "blue-green",
        "misty",
        "peaceful",
        "choppy",
      ],
      correctAnswerIndex: 0,
      explanation: "This social studies question examines peaceful. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 125 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "[Question 126 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "Which one of the following scenic views is not found in Netarhat ?",
      options: [
        "scintillating views of sunrises",
        "refugee camps",
        "beautiful sunrises and sunsets",
        "clusters of tall pine trees",
      ],
      correctAnswerIndex: 3,
      explanation: "This social studies question examines refugee camps. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "The phrase ‘hustle and bustle of cities’ implies :",
      options: [
        "(1) busy and noisy cities",
        "(2) beauty and eye catching views of cities",
        "(3) stunning sights and scenes of cities",
        "(4) peace and calm of cities P-II !SED-24-II! D 72Read the passage given below and answer the questions (129 - 1 35) that follow :",
      ],
      correctAnswerIndex: 2,
      explanation: "This social studies question examines (3) stunning sights and scenes of cities. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 129 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "Who among the three friends proposed the idea of meeting at the pool ten year s hence ?",
      options: [
        "Somi and Rusty",
        "Anil",
        "Somi",
        "Rusty",
      ],
      correctAnswerIndex: 1,
      explanation: "This social studies question examines Somi and Rusty. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Which one of the following options does not describe the pool in the stream ?",
      options: [
        "water trickling among fern and grasses",
        "rough rocks on the bed",
        "trickling waterfall down the rocks",
        "apple-green colour of the water",
      ],
      correctAnswerIndex: 3,
      explanation: "This social studies question examines rough rocks on the bed. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Which word can be the nearest synonym for the word ‘instinct’ ?",
      options: [
        "hatred",
        "affinity",
        "premonition",
        "inclination",
      ],
      correctAnswerIndex: 0,
      explanation: "This social studies question examines premonition. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "What brought the three boys together ?",
      options: [
        "their spirit of adventure",
        "their swimming talents",
        "their earnest attitudes",
        "their childhood mischiefs",
      ],
      correctAnswerIndex: 2,
      explanation: "This social studies question examines their childhood mischiefs. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 134 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "[Question 135 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "Ashwin knows Odia from his birth and he studies English and Hind i. Based on this statement, find which of the following statement is NOT true ?",
      options: [
        "His English learning is language acquisition.",
        "His Odia learning is language acquisition.",
        "His Hindi learning is language learning.",
        "His English learning is language learning.",
      ],
      correctAnswerIndex: 2,
      explanation: "This social studies question examines His Hindi learning is language learning.. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Instrumental motivation is when :",
      options: [
        "a person learns the language for writing a book.",
        "a person learns the language for utilitarian reason like employment.",
        "a person learns the language for being closer to the native speakers of th e language.",
        "a person learns the language for their communities religious and soc ial functions.",
      ],
      correctAnswerIndex: 1,
      explanation: "This social studies question examines a person learns the language for their communities. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Kripa and Karan are twins and speak a particular dialect of Manipur i. However they differ in their speech. What is their individual special way of speaking the dia lect known as ?",
      options: [
        "Manipuri",
        "Idiolect",
        "Dialect",
        "Speech act",
      ],
      correctAnswerIndex: 0,
      explanation: "This social studies question examines Manipuri. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "What is the status given to the English language in the Indian Consti tution ?",
      options: [
        "Language of statutory bodies",
        "Official language",
        "Associate Official language",
        "Foreign language",
      ],
      correctAnswerIndex: 1,
      explanation: "This social studies question examines Official language. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "A test which aims to identify an individual student’s specific ar eas of weakness and strength is known as :",
      options: [
        "Formative test",
        "Objective test",
        "Validity test",
        "Diagnostic test",
      ],
      correctAnswerIndex: 1,
      explanation: "This social studies question examines Validity test. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Aditi knows the rules of past perfect tense. But can’t use in a context. Wh at knowledge does she possess ?",
      options: [
        "Application of knowledge",
        "Language acquisition device",
        "Procedural knowledge",
        "Declarative knowledge",
      ],
      correctAnswerIndex: 3,
      explanation: "This social studies question examines Declarative knowledge. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Which of the following is NOT true of language ?",
      options: [
        "Some languages can only convey science and engineering better",
        "Language expresses identity",
        "Language is a repository of history",
        "Language contributes to the sum of human knowledge",
      ],
      correctAnswerIndex: 0,
      explanation: "This social studies question examines Some languages can only convey science and enginee. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "What are the stages involved in designing and doing a Project Work in language classroom ?",
      options: [
        "(1) Teacher and learners can design and do the project work any way they want to.",
        "(2) Forming groups, planning, collection of data, interpretation of d ata, writing the draft, identifying the topic, and finalization of the report.",
        "(3) Forming groups, identifying the topic, planning, collection of da ta, interpretation of data, writing the draft and finalization of the report.",
        "(4) Forming groups, identifying the topic, planning, collection of da ta, writing the draft, interpretation of data, and finalization of the report. P-II !SED-24-II! D 74144. Top-down approach to listening involves :",
      ],
      correctAnswerIndex: 2,
      explanation: "This social studies question examines (2) Forming groups, planning, collection of data, . Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 144 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "A teacher of Class VII wanted to give a writing task of writing a descr iption of a person. She went out of the classroom and brought a Hawker to her classroom with hi s basket. She requested him to be there for about seven minutes and then asked her learners to work in pair an d write a description of the person. What do you think the hawker in this activity known as ?",
      options: [
        "Materials",
        "Teaching Assistant",
        "A Hawker",
        "A participant in the activity",
      ],
      correctAnswerIndex: 0,
      explanation: "This social studies question examines A participant in the activity. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "A teacher of class VII wants her learners to read the short text with an u nderstanding of power and identity of the people and community presented in the text. What does t he teacher aim to promote among learners ?",
      options: [
        "Literary skills",
        "Language literacy",
        "Critical literacy",
        "Analytical reading",
      ],
      correctAnswerIndex: 2,
      explanation: "This social studies question examines Literary skills. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Which of the following is TRUE of the study of classical languag e as advocated by National Education Policy (NEP) 2020 ?",
      options: [
        "Study of classical language as a core language at the secondary sta ge.",
        "Study of classical language as an additional option during seco ndary stage.",
        "Study of classical language as an option under three language form ula.",
        "Study of classical language during the preparatory stage.",
      ],
      correctAnswerIndex: 1,
      explanation: "This social studies question examines Study of classical language as an additional optio. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Here is a text. Read and find out which language register does the text belon g to ? Suddenly, after the revolution, it seemed possible to change this. In many parts of the world including Europe and Asia, new ideas about individual rights and who controlled social power began to be discussed. In India, Raja Rammohan Roy and Derozio talked of the significance of the French Revolution. The developments in the colonies, in turn, reshaped thes e ideas of societal change.",
      options: [
        "Revolution register",
        "Science register",
        "Political register",
        "Social Science register",
      ],
      correctAnswerIndex: 3,
      explanation: "This social studies question examines Political register. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Subash, a teacher of class VIII regrets, “Language assessment generally does n ot give importance to receptive skills.” What does he mean by ‘receptive skills’?",
      options: [
        "Speaking and writing",
        "Listening and writing",
        "Speaking and reading",
        "Listening and reading",
      ],
      correctAnswerIndex: 3,
      explanation: "This social studies question examines Listening and reading. Understanding these concepts is crucial for Classes 6-8 social science curriculum. NCF 2005 emphasizes connecting social studies content to students' lives and developing critical thinking about society, history, and citizenship.",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 150 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.LANG2,
      topicId: "hindi-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    }
];
