import { MCQ, SubjectName } from '../../../types.js';

/**
 * CTET December 2024 - Paper II
 * Mathematics Questions (Q31-Q60)
 * 
 * Paper II Structure:
 * - Q1-30: CDP
 * - Q31-90: Science & Mathematics (60 questions total)
 *   - Q31-60: Mathematics (30 questions)
 *   - Q61-90: Science (30 questions)
 * - Q91-120: Language I (English)
 * - Q121-150: Language II (Hindi)
 */
export const mathematicsQuestions: MCQ[] = [
  {
      question: "Which of the following numbers is written in the standard form ?",
      options: [
        "83.7",
        "45",
        "8.5",
        "0.6",
      ],
      correctAnswerIndex: 2,
      explanation: "This mathematics problem requires understanding standard form representation. The correct answer '8.5' represents a number in standard decimal form. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "In a pentagon ABCDE, if each interior angle is equal, find the measure of each angle.",
      options: [
        "124°",
        "114°",
        "108°",
        "118°",
      ],
      correctAnswerIndex: 2,
      explanation: "This geometry problem requires calculating interior angles of a pentagon. The sum of interior angles = (5-2) × 180° = 540°. Each angle = 540°/5 = 108°. Understanding polygon properties is essential for geometry as per NCF 2005 mathematics curriculum.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "Which one of the following is the most appropriate feature of mathema tics textbooks at elementary level ?",
      options: [
        "(1) Concepts should be presented from concrete to abstract",
        "(2) The language of the book must be highly precise and technical",
        "(3) Books must contain a lot of similar questions to practice",
        "(4) Concepts should be presented from complex to simple (1)•ﬂ(2)¬(3)(4)•ﬂ",
      ],
      correctAnswerIndex: 0,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "A sum of ` 8000 becomes ` 9500 at 7.5% p.a. in x years at simple interest. What will be the amount of the sum in same time at 20% p.a, if interest is compounded yearly ? ` 8000",
      options: [
      "` 13824",
      "` 11616",
      "` 12144",
      "` 12672",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "The two corresponding angles formed by the intersection of two paral lel lines by a transversal are (3x−20°",
      options: [
        "150°",
        "90°",
        "110°",
        "130°",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "Which of the following is used to record students’ problem solving ability, measurement ability and experimentation ability ?",
      options: [
      "Teacher Diary",
      "Cumulative Record",
      "Report Card",
      "Anecdotal Record",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "The distance between the parallel sides AB and CD of a trapezium ABCD is 12 c m. If AB<CD, CD=24 cm and AD =BC=13 cm, then area of the trapezium (in cm2) is :",
      options: [
        "228",
        "123.5",
        "114",
        "247P-II !SED-24-II! D 15SPACE FOR ROUGH WORK / ⁄U»§ ∑§",
      ],
      correctAnswerIndex: 0,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "Which of the following is the correct sequence of rock cycle ?",
      options: [
        "(1) Igneous Rock, Magma, Metamorphic Rock",
        "(2) Sedimentary Rock, Metamorphic Rock, Magma",
        "(3) Igneous Rock, Metamorphic Rock, Sedimentary Rock",
        "(4) Magma, Metamorphic Rock, Sedimentary Rock",
      ],
      correctAnswerIndex: 0,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "A nine-digit number 565 x9274 y is divisible by number 88. Then, the value of (2 x+3y) is : ",
      options: [
        "22",
        "26",
        "25",
        "24",
      ],
      correctAnswerIndex: 2,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "Read the statements (A) and (R) carefully and choose the correct option. (A) :Using resources carefully and giving them time to get renewed is called r esource conservation. (R) :Balancing the need to use resources and also conserve them for the future i s called sustainable development. Options :",
      options: [
        "(1) (A) is false but (R) is true.",
        "(2) Both the statements (A) and (R) are true and (R) explains (A).",
        "(3) Both the statements (A) and (R) are true but (R) does not explain (A).",
        "(4) (A) is true but (R) is false. ∑§(A) (R) ∑§(A) :‚¥‚(R) :‚¥‚",
      ],
      correctAnswerIndex: 3,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "O is a point on line AB. Rays OC and OD are drawn on the same side of AB such that OC ⊥ OD, ∠AOC=x and ∠BOD=3x. Then, ∠BOD is equal to : ⁄",
      options: [
      " 1 67 2",
      " 1 22 2",
      "458",
      "608 P-II !SED-24-II! D 16 SPACE FOR ROUGH WORK / ⁄U»§",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "Consider the following statements about grasslands and choose the c orrect option. (A) Climate plays an important role in the formation of grasslands. (B) Annual rainfall is moderate in Prairies while velds could face drou ght in winter months. (C) The vegetation cover is sparse in Velds. (D) Velds lie in the Northern Hemisphere while Prairies in the Southern Hemisp here. Options :",
      options: [
        "Dispossession",
        "Hierarchy",
        "Diversification",
        "Inequality _______ ",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "If x = k, is the solution of the equation : 4 5 1 7 3 x x x − − − = + , then what is the value of 11 18 11 12 k k + − ?",
      options: [
      "4 9",
      "1 2",
      "3 4",
      "5 8",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "_______ refers to a situation where a person does not have resources and opportunities that are available to other persons.",
      options: [
      "Dispossession",
      "Hierarchy",
      "Diversification",
      "Inequality _______",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "[Question 45 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "Read the statements (A) and (R) and choose the appropriate option. (A) : Raja Rammohan Roy founded a reform association known as the Brahm o Sabha in Calcutta. (R) : He felt that changes were necessary in society and unjust practices needed to be done away with. Options :",
      options: [
        "(1) Both (A) and (R) are false.",
        "(2) Both (A) and (R) are true and (R) is the correct explanation of (A).",
        "(3) Both (A) and (R) are true but (R) is not the correct explanation of (A).",
        "(4) (A) is true but (R) is false. (A) •(R) ∑§(A) —⁄U(R) —ﬂ„ ◊",
      ],
      correctAnswerIndex: 3,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "The value of 31096÷(2704÷2)+0.6738+0.63+0.059−0.79 is equal to : 31096÷(2704÷2)+0.6738+0.63+0.059−0.79",
      options: [
      "24.5728",
      "23.6728",
      "23.5728",
      "24.6728",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "Cards bearing numbers 12, 13, 14, ... , 70, 71 (one number on one card) are kept in a box and then a card is drawn from the box without looking into it. What is the probability that the card drawn has the number which is not a prime ?",
      options: [
      "45 59",
      "1 4",
      "15 59",
      "3 4",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "Which of the following is true about common property resources ? (A) These are owned by government. (B) These are owned by private companies. (C) These are owned by communities. Options :",
      options: [
        "(1) Only (A) and (C) (2) Only (A) and (B)",
        "(3) Only (B) (4) Only (B) and (C) ‚(A)(B)(C)(1)∑§ﬂ‹ (A) ﬂ (C) (2) ∑§ﬂ‹ (A) ﬂ (B) (3)∑§ﬂ‹ (B) (4) ∑§ﬂ‹ (B) ﬂ (C) P-II !SED-24-II! D 4350. Maps can be best used for ___________.",
        "(1) Marking places where people have lived at different points in history",
        "(2) Arranging sequence of events in history",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "The distance covered (in metres) by a wheel of radius 25 cm in 350 rounds is (use π= 22 7 ) :",
      options: [
      "1100",
      "275",
      "550",
      "825 P-II !SED-24-II! D 19 SPACE FOR ROUGH WORK / ⁄U»§",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "Which of the following statements are true about the development of cot ton industries in the late 18th and early 19th century colonised India ? (a) Indian textile industry had to compete with British textiles in the E uropean and American markets. (b) British market was now available for Indian textiles. (c) Exporting textile goods to England became increasingly difficul t. (d) Bengal weavers were worst hit as English and European companies stop ped buying Indian textile. Options :",
      options: [
        "(1) (c) and (d) only (2) (a), (c) and (d) only",
        "(3) (b), (c) and (d) only (4) (a) and (b) only •∆U(a) (b) (c) ∑§¬«∏ ∑§(d) ’¥ª",
        "(1) ∑§ﬂ‹ (c) •(d) (2)∑§ﬂ‹ (a), (c) •(d)",
        "(3) ∑§ﬂ‹ (b), (c) •(d) (4)∑§ﬂ‹ (a) •(b) P-II !SED-24-II! D 4452. Consider the following statements (A) and (R) and choose the correct option. (A) :The Prairies are also known as the ‘Granaries of the world’. (R) :Scientific methods of cultivation and use of tractors, harvesters and combines has made South Africa a surplus food producer. Options :",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "Which of the following statement is correct about assessment ?",
      options: [
        "(1) Formative Assessment is used after the course completion to assign th e grades.",
        "(2) Assessment as learning generates opportunities for self-assessment an d peer assessment.",
        "(3) Summative Assessment helps to know to what extent the instructional objectives have been achieved while teaching a concept.",
        "(4) ‘Assessment for learning’ is a process with no scope of giving feedba ck. •",
      ],
      correctAnswerIndex: 3,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "Diversity came with something new and different due to __________.",
      options: [
        "(1) Homogeneous population (2) Intermixing of cultures",
        "(3) Genetic composition (4) Similarities and identical traits (1)‚¡(2) ‚¥S∑(3)•(4) (A) Compensate for low grades and marks scored in School and University examinations, because of which people were not able to compete. (B) Compensate for years of historical suppression and educational dep rivation. (C) Appease people for political support and rally as vote banks. Options :",
        "(1) Both (B) and (C) (2) Only (A)",
        "(3) Only (B) (4) Both (A) and (C) (A) (B) ﬂ·(C) ﬂ",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "[Question 54 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "Read the statements (A) and (R) considering the art forms in colonial India. Assertion (A) :Colonial rule introduced several new art forms, styles and techniques. Reason (R) : These were creatively adapted by Indian artists for local patrons an d markets. Choose the correct option.",
      options: [
        "(1) Both (A) and (R) are false.",
        "(2) Both (A) and (R) are true and (R) is the correct explanation of (A).",
        "(3) Both (A) and (R) are true but (R) is not the correct explanation of (A).",
        "(4) (A) is true but (R) is false. •(A) ∞ﬂ¥ (R) ∑§(A) :•(R) :",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "If x is the smallest number which is to be subtracted from 2605 to make it a perfect square, then the value of (4 x+7) is :",
      options: [
        "31",
        "11",
        "23",
        "27",
      ],
      correctAnswerIndex: 2,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "Read the given Assertion (A) and Reason (R) statements and choose the appropriate option. Assertion (A) :By the late 19th century, the craft of iron smelting declined and in most villages, furnaces fell into disuse. Reason (R) : The iron smelters had to pay a very high tax to the Forest Department that reduced their income. Choose the correct option.",
      options: [
        "(1) Both (A) and (R) are false.",
        "(2) Both (A) and (R) are true and (R) is the correct explanation of (A).",
        "(3) Both (A) and (R) are true but (R) is not the correct explanation of (A).",
        "(4) (A) is true but (R) is false. (A) ∞ﬂ¥ ∑§(R) ∑§(A) :©(R) : ‹",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "Nitu is always confused in identifying the transformations. Her mathematics teacher helped her by giving one simple word for each transformation namely : Reflection, Rotation, Translation and Enlargement. Which of the following represents the correct sequence of meaning of each transformation as given above ?",
      options: [
      "Flip, Slide, Turn and Bigger Figure",
      "Turn, Slide, Flip and Bigger Figure",
      "Flip, Turn, Slide and Bigger Figure",
      "",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "medium",
    },
  {
      question: "On which of the following dates Gandhiji asked the Indian people to o bserve a day of non-violent opposition to the ‘Rowlatt Act’?",
      options: [
        "(1) 6 December 1919 (2) 6 April 1919",
        "(3) 13 April 1919 (4) 15 December 1919",
        "(1) 6 (2) 6 •",
        "(3) 13 •(4) 15",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    },
  {
      question: "When it is 1:00 p.m. at Greenwich, what time will it be at 60 U/c5243 West and 60 U/c5243 East respectively ?",
      options: [
        "(1) 9:00 p.m. and 5:00 a.m. (2) 5:00 p.m. and 9:00 a.m.",
        "(3) 9:00 a.m. and 5:00 p.m. (4) 5:00 a.m. and 9:00 p.m. ¡’ ª˝",
        "(1) 9:00 •¬⁄U(2) 5:00 •¬⁄U",
        "(3) 9:00 ¬(4) 5:00 ¬(A) and (B) and choose the correct option of the following. Statement (A) : Summative assessment monitors the learner’s progress throughout t he teaching- learning process. Statement (B) : Formative assessment is conducted at the end of the course.",
      ],
      correctAnswerIndex: 2,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.MATH,
      topicId: "mathematics",
      subTopicId: "problem-solving",
      difficulty: "easy",
    }
];
