import { MCQ, SubjectName } from '../../../types.js';

/**
 * CTET December 2024 - Paper II
 * Science Questions (Q61-Q90)
 * 
 * Paper II Structure:
 * - Q1-30: CDP
 * - Q31-90: Science & Mathematics (60 questions total)
 *   - Q31-60: Mathematics (30 questions)
 *   - Q61-90: Science (30 questions)
 * - Q91-120: Language I (English)
 * - Q121-150: Language II (Hindi)
 */
export const scienceQuestions: MCQ[] = [
  {
      question: "Assertion (A) :Achievement in STEM related courses is influenced by gender. Reason (R) : Problem solving strategies used by boys and girls are different.",
      options: [
        "(1) Both (A) and (R) are false.",
        "(2) Both (A) and (R) are true and (R) is correct explanation of (A).",
        "(3) Both (A) and (R) are true but (R) is not correct explanation of (A).",
        "(4) (A) is true and (R) is false. •(A) : STEM (S≈◊) ‚¥’¥(¡¥«U⁄U) m(R) : ‹«∏∑§ ∞ﬂ¥ ‹«∏",
      ],
      correctAnswerIndex: 2,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "(A) is a technique of vegetative propagation in which a part of the stem or a young branch of a plant is pulled and buried in moist soil, such that the branch i s still attached to the Parent Plant. After some time, roots develop in the buried part and it grows int o a new plant. (B) is an example of plant usually grown through this technique. (A) and (B) respectively are :",
      options: [
        "Layering, Jasmine",
        "Cutting, Potato",
        "Grafting, Rose",
        "∑§",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Select the reason behind the low wages paid for agricultural labourers.",
      options: [
      "They are satisfied with wages prevailing in the market.",
      "They are not skilled.",
      "They depend on land owners for a regular work.",
      "Most of them do not have their own land.",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "Social Science curricular activities can be made more engaging for s tudents by __________.",
      options: [
        "(1) reducing critical thinking and discussion in favour of lectur es.",
        "(2) incorporating technology and multimedia resources.",
        "(3) focusing only on the most important historical events and figur es.",
        "(4) emphasizing memorization of facts and figures. ¿U",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Match the following and choose the correct option. A B (A) Narration charts (i) steps in a process (B) Relationship charts (ii) data in the form of table (C) Flow charts (iii) historical development (D) Tabulation charts (iv) show cause-and-effect relationships",
      options: [
        "(1) (A)-(ii), (B)-(iii), (C)-(iv), (D)-(i)",
        "(2) (A)-(iii), (B)-(iv), (C)-(i), (D)-(ii)",
        "(3) (A)-(iv), (B)-(ii), (C)-(i), (D)-(iii)",
        "(4) (A)-(iv), (B)-(iii), (C)-(ii), (D)-(i) (A) (i) (B) ‚¥’¥(ii)(C) (iii)∞(D) ‚(iv)∑§",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "[Question 66 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "Which one of the following statements is correct regarding the natur e of Social Science ? (A) Social Science is a dynamic subject that generates debate and discuss ion. (B) In Social Science only individual human relations are considered a nd not the accounts of individual actions. (C) Social Science is primarily interdisciplinary subject with a foc us on discovery and experimentation. (D) The scope of Social Science is very narrow and hence it is fit to teach it o nly at the primary level. Options :",
      options: [
        "(1) (A) and (B) only (2) (A) and (C) only",
        "(3) (C) and (D) only (4) (A), (B) and (C) only ‚(A)‚(B)‚(C)‚(D)‚(1)∑§ﬂ‹ (A) •(B) (2) ∑§ﬂ‹ (A) •(C) (3)∑§ﬂ‹ (C) •(D) (4) ∑§ﬂ‹ (A), (B) •(C) P-II !SED-24-II! D 5168. Sixty-Percent weightage is given by the teacher to open-ended questions i n a Social Science question paper. Which skill does the teacher want to test among students throug h this strategy ? (A) Writing skills only (B) Intrapersonal skills (C) Logical thinking and creative skills (D) Application and presentation skills Options :",
        "(1) (B), (C) and (D) only (2) (A) and (B) only",
        "(3) (C) and (D) only (4) (A), (B) and (C) only (A) ∑§ﬂ‹ ‹π(B) •¥(C) (D) •",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "The following activity is done in the class VII : Students are given four iron bars out of which two are bar magnets. They are asked to identify the bar magnets. Which of the following process skills can be promoted through this activity ?",
      options: [
      "Observation, Estimation, Experimentation, Controlling variables.",
      "Observation, Formulating hypothesis, Measuring",
      "Observation, Classification, Inferring",
      "Observation, Classification, Communication, Measurement",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "Which of the following aspect is considered in the Right to Educati on Act, 2009 as part of evaluation procedures ? (A) Confirm with the values enshrined in the Indian Constitution (B) Examination should involve mainly summative assessment (C) Development of the physical abilities of learners to the fullest extent (D) Examinations are conducted within the school premises Options :",
      options: [
        "(1) (A) and (C) only (2) (A), (B) and (C) only",
        "(3) (A), (C) and (D) only (4) (A) and (B) only (A) (B) ¬⁄U(C) (D) ¬⁄U",
        "(1) ∑§ﬂ‹ (A) •(C) (2)∑§ﬂ‹ (A), (B) •(C)",
        "(3) ∑§ﬂ‹ (A), (C) •(D) (4)∑§ﬂ‹ (A) •(B) P-II !SED-24-II! D 5270. Read the statements (A) and (B) and choose the appropriate option. Statement (A) :Contemporary challenges to the principle of a democratic society are c onflicts such as those between individual rights and social responsibilit ies. Statement (B) :Within a social science classroom, conflict resolution approach c ould be used to engage students to study ‘Problems of democracy’.",
      ],
      correctAnswerIndex: 0,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "The density of medium A is more than medium B but less than medium C. In whi ch medium does the sound travels fastest ?",
      options: [
        "(1) Can’t be inferred from this information (2) A",
        "(3) B (4) C ◊",
        "(1) (2) A",
        "(3) B (4) C P-II !SED-24-II! D 2871.Complete the following table : Atomic number Mass number No. of electrons No. of prot ons No. of neutrons 9 A B C 10 D 24 E 12 F A, B, C, D, E, F respectively are :",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Indian Constitution lays down _________.",
      options: [
        "norms for participation of people into social movements that seek t o challenge the Government",
        "the national curriculum framework",
        "the basic laws or rules that have to be followed by everyone",
        "the structure of religious institutions",
      ],
      correctAnswerIndex: 2,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Assertion (A) :Convex mirrors are used as rearview-mirrors in vehicles. Reason (R1 ): They form erect and enlarged image. Reason (R2) : They have wider field of view.",
      options: [
        "(1) (A) is true but neither (R1) nor (R2) are correct explanation for (A).",
        "(2) (A) is true and both (R1) and (R2) are correct explanations for (A).",
        "(3) (A) is true and only (R1) is correct explanation for (A).",
        "(4) (A) is true and only (R2) is correct explanation for (A). •(A) :•ﬂ◊(©((R1) : ﬂ ™§(R2) : ©",
      ],
      correctAnswerIndex: 0,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Which of the following topics are highly appropriate for middle l evel students ? (A) Contribution of Mahatma Gandhi in history. (B) Economic development of India. (C) Status of Women in present scenario. (D) Reasons for population growth. Options :",
      options: [
        "(1) (A), (C) and (D) only (2) (A) and (C) only",
        "(3) (A) and (D) only (4) (B), (C) and (D) only (A) (B) (C) ﬂ(D) ¡",
        "(1) ∑§ﬂ‹ (A), (C) •(D) (2)∑§ﬂ‹ (A) •(C)",
        "(3) ∑§ﬂ‹ (A) •(D) (4)∑§ﬂ‹ (B), (C) •(D) P-II !SED-24-II! D 5474. How can a Social Studies teacher develop social values among student s ? (i) Developing sense of discipline (ii) Behaving in the appropriate manner in school/class (iii) Asking Students to watch commercial movies (iv) Follow appropriate democratic values in class/school setting Choose the correct option.",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Which of the following statements is true ?",
      options: [
      "Soil with low water holding capacity has good aeration and high percolation rate.",
      "Soil with low water holding capacity has poor aeration and high percolation rate.",
      "Soil with low water holding capacity has good aeration and low percolation rate.",
      "Soil with low water holding capacity has poor aeration and low percolation rate.",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "Which one of the following teaching methods are suitable to overcome t he teaching challenges faced in Social Sciences ? (A) From Specific to General (B) From Complex to General (C) From Known to Unknown (D) From Analysis to Synthesis Choose the correct option.",
      options: [
        "(1) (A), (B) and (D) (2) (A), (B) and (C)",
        "(3) (B), (C) and (D) (4) (A), (C) and (D) ((A)(B) ¡(C)(D)",
        "(1) (A), (B) •(D) (2) (A), (B) •(C)",
        "(3) (B), (C) •(D) (4) (A), (C) •(D) P-II !SED-24-II! D 5576. What does it mean to use the dialectic approach to teaching in the Soci al Science classroom ?",
      ],
      correctAnswerIndex: 3,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Which of the following statements are true in the context of respirati on in whales and dolphins ? (A) They cannot use dissolved Oxygen. (B) They have gills. (C) They have large nostrils. (D) They often come up to the water surface to breathe.",
      options: [
        "Journal writing, Field trips",
        "Portfolios, Anecdotal records",
        "Projects, Portfolios",
        "Anecdotal records, Journal writing",
      ],
      correctAnswerIndex: 2,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Which of the following questions asked by the teacher come under the categ ory of exploratory and critical questions ? (A) What is the southernmost part of the Himalayas called ? (B) Is the Sun a star ? Why ? (C) Why does more population reside in the Northern plains ? (D) Between which two countries is the Pak Water Treaty located ? Options :",
      options: [
        "(1) (C) only (2) (B) and (C)",
        "(3) (B) only (4) (A), (B), (C) and (D) ∑§ˇ(A) (B) (C) ©(D) ¬",
        "(1) ∑§ﬂ‹ (C) (2) (B) •(C)",
        "(3) ∑§ﬂ‹ (B) (4) (A), (B), (C) •(D) P-II !SED-24-II! D 5678. Small workshops and factories prefer to employ casual workers beca use _________. (A) state has already taken care of workers’ benefits (B) they can be fired without any prior notice (C) most of them are not literate (D) they could be paid lowest possible wages Options :",
      ],
      correctAnswerIndex: 2,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Assertion (A) :Nichrome is used as a heating element in devices like electric toaster and el ectric geyser. Reason (R) : Nichrome has high melting point and low resistivity.",
      options: [
        "(1) Both (A) and (R) are false",
        "(2) Both (A) and (R) are true and (R) is correct explanation for (A)",
        "(3) Both (A) and (R) are true but (R) is not correct explanation for (A)",
        "(4) (A) is true and (R) is false •(A) :(R) :",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Nelson Mandela spent 28 years of imprisonment along with thousand s of black and coloured people.",
      options: [
        "(1) to raise voice against King and royal monarchy.",
        "(2) for opposing apartheid and struggle against policies of segregat ion.",
        "(3) to get punishment for offence.",
        "(4) to get powerful positions in Government. (1)⁄U(2)⁄¥Uª (3)•¬⁄U(4)‚⁄U∑§",
      ],
      correctAnswerIndex: 0,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "On the basis of the following information identify the substances which give flame on burning : Substance State Vapourises on burning A Solid No B Liquid Yes C Solid Yes D Liquid No",
      options: [
      "C and D",
      "A and D",
      "A and B",
      "C",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "[Question 81 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "Consider the following statements (A) and (B). (A) The Government of India Act 1909, allowed for some elected representation s ystem in India. (B) Through Government of India Act 1909 all adults were given the right to vote. Choose the correct option.",
      options: [
        "(1) Neither (A) nor (B) is true (2) Only (A) is true",
        "(3) Only (B) is true (4) Both (A) and (B) are true (A) (B) ∑§(A) 1909 ◊¥ ’(B) 1909 ∑§ ªﬂ",
        "(1) (A) ‚„(B) ‚„(2)∑§ﬂ‹ (A) ‚„",
        "(3) ∑§ﬂ‹ (B) ‚„(4) (A) (B) (A) It helps students to pass exam. (B) It allows students to guess the correct answer (C) It helps students memorize information more easily (D) It prepare students for higher-level-thinking (E) It promotes problem-solving abilities Choose the correct option :",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Which of the following questions is a divergent question ?",
      options: [
      "What would happen to gravity if the size of earth is reduced to half ?",
      "Why does a ball thrown up comes down ?",
      "What if there was no gravity on the earth ?",
      "How does gravity vary with the altitude ?",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "Which would be the best teaching pedagogy to understand the trends in p overty in Indian States and Union Territories ?",
      options: [
        "(1) Brainstorming (2) Field trip",
        "(3) Debate (4) Secondary data analysis (1)(’˝(2) ˇ(3)ﬂ(4) (A) Poshan Abhiyan is an important programme to improve the nutriti on level of Indian children. Examine the statement with evidences. (B) Colonial rule in India for two centuries left India with irreversibl e social change in India. Do you agree with this statement ? Explain. (C) Describe the important features of Jan Dhan Yojana. (D) Poverty and unemployment in India has declined in the post 1991 India . Justify this statement. Options :",
        "(1) Only (C) and (D) (2) Only (A) and (B)",
        "(3) Only (A), (B) and (C) (4) Only (B), (C) and (D) (A) ¬(B) (C) ¡(D) 1991 ∑§ ©",
      ],
      correctAnswerIndex: 1,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Which of the following statements is correct ? S1 :The normal temperature of the human body is 37 °",
      options: [
        "(1) S1 is inference and S2 is observation",
        "(2) Both S1 and S2 are observation",
        "(3) Both S1 and S2 are inferences",
        "(4) S1 is observation and S2 is inference",
      ],
      correctAnswerIndex: 0,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "The teacher divides the children of her class into 4 groups and gives th em to write the names of the sources of water and then discusses the sources of water with each grou p. Which of the following he/she is attempting first as part of 5E approach to lesson plan ?",
      options: [
        "(1) Engage (2) Explore (3) Evaluate (4) Explain",
        "(1) ‚¥‹(2) •(3) ◊",
        "(1) Textbook (2) Newspaper articles",
        "(3) Field trip (4) Biography  (1)¬(2) •π’(3)•(4) ¡",
      ],
      correctAnswerIndex: 2,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "Which of the following statements is/are true regarding nature of sc ience ? (A) Scientific ideas are not affected by cultural context. (B) There is no single scientific method.",
      options: [
        "(1) Both (A) and (B) are false (2) Both (A) and (B) are true",
        "(3) (A) is true and (B) is false (4) (A) is false and (B) is true (A) ﬂ(B) ∑§(¬h",
        "(1) (A) •(B) (2) (A) •(B)",
        "(3) (A) ‚„(B) ª‹(4) (A) ª‹(B) ‚„",
      ],
      correctAnswerIndex: 0,
      explanation: "This question tests understanding of the concept. The solution involves proper analysis and application of knowledge of context, vocabulary, and language usage. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences.",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "easy",
    },
  {
      question: "While ice melts at 0EC, its temperature :",
      options: [
      "first decreases and then remains same",
      "increases",
      "decreases",
      "",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "In a field trip which is the first skill to be developed among students ?",
      options: [
      "Reasoning skill",
      "Analytical skill",
      "Observation skill",
      "Experimentation skill",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    },
  {
      question: "Read the following statements in the context of Laws and theories in Science : S1 : Laws are generalisation statement whereas theories are explanations. S2 : Laws are very old and theories are contemporary. S3 : Laws can’t be changed whereas theories are subject to change.",
      options: [
      "S3 is true whereas S1 and S2 are false",
      "S1 is true; S2 and S3 are false",
      "S1 and S2 are true whereas S3 is false",
      "S1 and S3 are true whereas S2 is false",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.SCIENCE,
      topicId: "science",
      subTopicId: "concepts",
      difficulty: "medium",
    }
];
