import { MCQ, SubjectName } from '../../../types.js';

/**
 * CTET December 2024 - Paper II
 * Language I (English) Questions (Q91-Q120)
 * 
 * Paper II Structure:
 * - Q1-30: CDP
 * - Q31-90: Science & Mathematics (60 questions)
 * - Q91-120: Language I (English) - 30 questions
 * - Q121-150: Language II (Hindi) - 30 questions
 */
export const languageIEnglishQuestions: MCQ[] = [
  {
      question: "[Question 91 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "[Question 92 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "[Question 93 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "[Question 94 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "According to the writer, it is important to pay attention to the col our scheme of your home because :",
      options: [
        "the monotonous shades add life to the rooms",
        "the ambience created makes it look boring",
        "it reflects the personality of the owner",
        "the walls reveal the secrets of your life",
      ],
      correctAnswerIndex: 1,
      explanation: "This language comprehension question tests understanding of reading passages and author's intent. The correct answer shows proper interpretation of the text's meaning and context. Effective reading comprehension involves analyzing text structure, identifying main ideas, and making inferences as emphasized in NCF 2005.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 96 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "Complete the given word analogy : monotonous : dull :: ambience : ? .",
      options: [
        "weather",
        "room",
        "temperature",
        "aura",
      ],
      correctAnswerIndex: 1,
      explanation: "This mathematics problem requires aura. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Some people draw colourful sceneries on their home walls to :",
      options: [
        "blend dark and light colours",
        "give a deeper significance to their home",
        "bring nature into their homes",
        "create a sense of space",
      ],
      correctAnswerIndex: 2,
      explanation: "This mathematics problem requires blend dark and light colours. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 99 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Answer is option 2]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "The poetic devices in line 2 and line 4 are :",
      options: [
        "metaphor and simile",
        "metaphor and personification",
        "hyperbole and metaphor",
        "simile and alliteration",
      ],
      correctAnswerIndex: 1,
      explanation: "This mathematics problem requires hyperbole and metaphor. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "What is the overall tone of the poem ?",
      options: [
        "nostalgic and admiration",
        "annoyance and anger",
        "pitiful and sympathetic",
        "disgust and animosity",
      ],
      correctAnswerIndex: 1,
      explanation: "This mathematics problem requires disgust and animosity. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Complete the word analogy : coarse : rough :: snug : ? .",
      options: [
        "comfortable",
        "lazy",
        "perfect",
        "lethal",
      ],
      correctAnswerIndex: 1,
      explanation: "This mathematics problem requires comfortable. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "How does the speaker’s father feel about his son’s choice of career ?",
      options: [
        "He is ambivalent towards the choice.",
        "The poem doesn’t make it clear.",
        "He wishes, his son choose a more practical path.",
        "He is glad his son is not a farmer.",
      ],
      correctAnswerIndex: 2,
      explanation: "This mathematics problem requires The poem doesn’t make it clear.. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "In the second stanza, the poet is observing :",
      options: [
        "potato growers in the countryside",
        "a gardener tending flower beds",
        "his father digging potatoes",
        "farmers in the fields",
      ],
      correctAnswerIndex: 2,
      explanation: "This mathematics problem requires his father digging potatoes. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "‘. . . . . loving their cool hardness in our hands’. What is the speaker referri ng to the given line ?",
      options: [
        "(1) the potato drills (2) the gun",
        "(3) the handles of the spade (4) the potatoes P-II !SED-24-II! D 64106. ‘Authenticity of materials’ refers to :",
        "(1) materials which children bring from home.",
        "(2) materials written by the teacher for her class.",
      ],
      correctAnswerIndex: 1,
      explanation: "This mathematics problem requires (2) materials written by the teacher for her class. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 106 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 1]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "Aparna, a learner of class V understands that listening involves li stening to each sound, words, then sentences to get the meaning of the speech or an audio. Which approach /strategy she believes in for learning to listen ?",
      options: [
        "It is neither top-down nor bottom-up approach",
        "Top-down approach",
        "Bottom-up approach",
        "Both top-down and bottom-up approach",
      ],
      correctAnswerIndex: 2,
      explanation: "This mathematics problem requires Top-down approach. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "What is ‘systemic competence’ in language learning ?",
      options: [
        "Understanding that all human have a systems of many languages.",
        "Understanding and applying that language works as a system.",
        "Understanding and applying that languages have a grammatical sy stem.",
        "Understanding that all languages have a common structural syst em.",
      ],
      correctAnswerIndex: 1,
      explanation: "This mathematics problem requires Understanding and applying that languages have a g. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Here is text or some statements. Find out which language register does thi s text represent ? The Indian Constitution recognises every person as equal. This means th at every individual in the country, including male and female, person from all castes, relig ions, tribes, educational and economic background are recognised as equal. This is not to say that inequity ceases to exist. It doesn’t. But at least, in democratic India, the principle of the equalit y of all persons is recognised.",
      options: [
        "Scientific register",
        "Politic register",
        "Social Science register",
        "Legal register",
      ],
      correctAnswerIndex: 2,
      explanation: "This mathematics problem requires Legal register. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "A teacher of class VI does a warm up activity to connect their previou s knowledge and experience with the text they would read. She asks her learners to look at the illustr ations of the reading text (the story) before she begin to teach the text. What does she want her learners t o do ?",
      options: [
        "Make them understand the illustrations.",
        "Visualize the story through the illustrations.",
        "Appreciate the illustrations.",
        "Make prediction about the reading text.",
      ],
      correctAnswerIndex: 3,
      explanation: "This mathematics problem requires Make them understand the illustrations.. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "A continuous record of instances of learning by the learners is know n as :",
      options: [
        "Diagnostic test",
        "Portfolio",
        "Continuous Comprehensive Assessment",
        "Proficiency assessment",
      ],
      correctAnswerIndex: 1,
      explanation: "This mathematics problem requires Portfolio. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "((1)(2)(3)¬∆U(4)’",
      options: [
        "",
        "(2) ",
        "(3) ",
        "",
      ],
      correctAnswerIndex: 0,
      explanation: "This mathematics problem requires (3) . The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 113 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending - Answer is option 4]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    },
  {
      question: "Which of the following language is NOT a classical language ?",
      options: [
        "Hindi",
        "Tamil",
        "Sanskrit",
        "Telugu",
      ],
      correctAnswerIndex: 0,
      explanation: "This mathematics problem requires Hindi. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Which of the following is NOT true of the National Education Poli cy (NEP) 2020 on the study of foreign languages ?",
      options: [
        "French is one of the language recommended to be studied as an additional o ption.",
        "Study of foreign languages as an additional option during the sec ondary stage.",
        "Study of foreign languages included as one of the languages under the t hree language formula.",
        "Foreign language does not include in the three languages studied under t hree language formula.",
      ],
      correctAnswerIndex: 2,
      explanation: "This mathematics problem requires Study of foreign languages as an additional option. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Which of the following refers to ‘Knowing about language’?",
      options: [
        "Strategic competence",
        "Declarative knowledge",
        "Procedural knowledge",
        "Grammatical knowledge",
      ],
      correctAnswerIndex: 3,
      explanation: "This mathematics problem requires Procedural knowledge. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "A teacher of class VI develops the following task for a speaking acti vity. Speak five sentences about desert and its climatic condition s. Is it a good task or not a good task ? Select from option your respon se and reason for the same.",
      options: [
        "It is not a good task because it lacks context as there is no input for speaking about desert and its conditions.",
        "It is a good task because the learners may have studied about desert in th eir geography class and will have inputs to speak.",
        "It is a good task because it makes the learner to talk about something i .e the desert.",
        "It is not a good task because some of the learners may not know about des ert.",
      ],
      correctAnswerIndex: 1,
      explanation: "This mathematics problem requires It is not a good task because some of the learners. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Which of the following statements is true of a dialect of a language ?",
      options: [
        "Sometime different social group may speak different dialects of the sa me language.",
        "Dialects of language vary from region to region.",
        "Speakers of different dialects of one language can understand the other dialect speaker.",
        "A dialect is a bigger category and language is a smaller category.",
      ],
      correctAnswerIndex: 0,
      explanation: "This mathematics problem requires Sometime different social group may speak differen. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "Which of the following tasks promotes integrated learning skills ?",
      options: [
        "Writing an article",
        "Role play",
        "Assignment",
        "Project work",
      ],
      correctAnswerIndex: 3,
      explanation: "This mathematics problem requires Role play. The solution involves systematic problem-solving and application of mathematical concepts appropriate for Classes 6-8. Understanding such concepts is fundamental to the mathematics curriculum as per NCF 2005's emphasis on mathematical thinking and reasoning.",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "easy",
    },
  {
      question: "[Question 120 - Manual entry needed from PDF]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Answer is option 3]",
      subjectName: SubjectName.LANG1,
      topicId: "english-language",
      subTopicId: "comprehension",
      difficulty: "medium",
    }
];
