import { MCQ, SubjectName } from '../../../types.js';

/**
 * CTET December 2024 - Paper II Track B
 * Social Studies Questions - Part 2 (Q61-Q90)
 * 
 * Paper II Track B Structure:
 * - Q1-30: CDP
 * - Q31-90: Social Studies (60 questions)
 *   - Q31-60: Social Studies Part 1 (30 questions)
 *   - Q61-90: Social Studies Part 2 (30 questions)
 * - Q91-120: Language I (English)
 * - Q121-150: Language II (Hindi)
 * 
 * Topics covered: History, Geography, Civics, Economics
 * Aligned with NCF 2005 and Classes 6-8 curriculum
 */
export const socialStudiesPart2Questions: MCQ[] = [
  {
      question: "[Question 61 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "world-history",
      difficulty: "medium",
    },
  {
      question: "[Question 62 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "environment",
      difficulty: "easy",
    },
  {
      question: "[Question 63 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "political-parties",
      difficulty: "medium",
    },
  {
      question: "[Question 64 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "globalization",
      difficulty: "medium",
    },
  {
      question: "[Question 65 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "post-independence",
      difficulty: "easy",
    },
  {
      question: "[Question 66 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "agriculture-patterns",
      difficulty: "medium",
    },
  {
      question: "[Question 67 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "secularism",
      difficulty: "medium",
    },
  {
      question: "[Question 68 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "poverty",
      difficulty: "easy",
    },
  {
      question: "[Question 69 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "social-reforms",
      difficulty: "medium",
    },
  {
      question: "[Question 70 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "soil-types",
      difficulty: "medium",
    },
  {
      question: "[Question 71 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "elections",
      difficulty: "easy",
    },
  {
      question: "[Question 72 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "unemployment",
      difficulty: "medium",
    },
  {
      question: "[Question 73 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "indian-culture",
      difficulty: "medium",
    },
  {
      question: "[Question 74 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "human-settlements",
      difficulty: "easy",
    },
  {
      question: "[Question 75 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "media-democracy",
      difficulty: "medium",
    },
  {
      question: "[Question 76 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "consumer-rights",
      difficulty: "medium",
    },
  {
      question: "[Question 77 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "renaissance-reformation",
      difficulty: "easy",
    },
  {
      question: "[Question 78 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "disaster-management",
      difficulty: "medium",
    },
  {
      question: "[Question 79 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "marginalization",
      difficulty: "medium",
    },
  {
      question: "[Question 80 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "sustainable-development",
      difficulty: "easy",
    },
  {
      question: "[Question 81 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "industrial-revolution",
      difficulty: "medium",
    },
  {
      question: "[Question 82 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "climate-change",
      difficulty: "medium",
    },
  {
      question: "[Question 83 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "gender-equality",
      difficulty: "easy",
    },
  {
      question: "[Question 84 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "inflation",
      difficulty: "medium",
    },
  {
      question: "[Question 85 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "colonial-india",
      difficulty: "medium",
    },
  {
      question: "[Question 86 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "map-reading",
      difficulty: "easy",
    },
  {
      question: "[Question 87 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "rule-of-law",
      difficulty: "medium",
    },
  {
      question: "[Question 88 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "public-finance",
      difficulty: "medium",
    },
  {
      question: "[Question 89 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "united-nations",
      difficulty: "easy",
    },
  {
      question: "[Question 90 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "economic-geography",
      difficulty: "medium",
    },
];
