import { MCQ, SubjectName } from '../../../types.js';

/**
 * CTET December 2024 - Paper II Track B
 * Social Studies Questions - Part 1 (Q31-Q60)
 * 
 * Paper II Track B Structure:
 * - Q1-30: CDP
 * - Q31-90: Social Studies (60 questions)
 *   - Q31-60: Social Studies Part 1 (30 questions)
 *   - Q61-90: Social Studies Part 2 (30 questions)
 * - Q91-120: Language I (English)
 * - Q121-150: Language II (Hindi)
 * 
 * Topics covered: History, Geography, Civics, Economics
 * Aligned with NCF 2005 and Classes 6-8 curriculum
 */
export const socialStudiesPart1Questions: MCQ[] = [
  {
      question: "[Question 31 - Social Studies - History - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending - Covers Classes 6-8 Social Science curriculum as per NCF 2005]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "ancient-medieval-india",
      difficulty: "medium",
    },
  {
      question: "[Question 32 - Social Studies - Geography - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending - Geography concepts for middle school]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "earth-resources",
      difficulty: "medium",
    },
  {
      question: "[Question 33 - Social Studies - Civics - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending - Civics and governance]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "indian-constitution",
      difficulty: "easy",
    },
  {
      question: "[Question 34 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "indian-freedom-movement",
      difficulty: "medium",
    },
  {
      question: "[Question 35 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "climate-vegetation",
      difficulty: "medium",
    },
  {
      question: "[Question 36 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "local-government",
      difficulty: "easy",
    },
  {
      question: "[Question 37 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "resources-development",
      difficulty: "medium",
    },
  {
      question: "[Question 38 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "medieval-india",
      difficulty: "medium",
    },
  {
      question: "[Question 39 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "natural-resources",
      difficulty: "easy",
    },
  {
      question: "[Question 40 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "fundamental-rights",
      difficulty: "medium",
    },
  {
      question: "[Question 41 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "modern-india",
      difficulty: "medium",
    },
  {
      question: "[Question 42 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "population",
      difficulty: "easy",
    },
  {
      question: "[Question 43 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "agriculture",
      difficulty: "medium",
    },
  {
      question: "[Question 44 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "democracy",
      difficulty: "medium",
    },
  {
      question: "[Question 45 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "ancient-india",
      difficulty: "easy",
    },
  {
      question: "[Question 46 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "landforms",
      difficulty: "medium",
    },
  {
      question: "[Question 47 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "industries",
      difficulty: "medium",
    },
  {
      question: "[Question 48 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "state-government",
      difficulty: "easy",
    },
  {
      question: "[Question 49 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "british-rule",
      difficulty: "medium",
    },
  {
      question: "[Question 50 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "water-resources",
      difficulty: "medium",
    },
  {
      question: "[Question 51 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "trade",
      difficulty: "easy",
    },
  {
      question: "[Question 52 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "union-government",
      difficulty: "medium",
    },
  {
      question: "[Question 53 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "cultural-heritage",
      difficulty: "medium",
    },
  {
      question: "[Question 54 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "minerals",
      difficulty: "easy",
    },
  {
      question: "[Question 55 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "economic-development",
      difficulty: "medium",
    },
  {
      question: "[Question 56 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "judiciary",
      difficulty: "medium",
    },
  {
      question: "[Question 57 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 0,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "history",
      subTopicId: "nationalism",
      difficulty: "easy",
    },
  {
      question: "[Question 58 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 1,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "geography",
      subTopicId: "transportation",
      difficulty: "medium",
    },
  {
      question: "[Question 59 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 2,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "economics",
      subTopicId: "money-banking",
      difficulty: "medium",
    },
  {
      question: "[Question 60 - Social Studies - Manual entry needed]",
      options: [
        "[Option 1]",
        "[Option 2]",
        "[Option 3]",
        "[Option 4]",
      ],
      correctAnswerIndex: 3,
      explanation: "[Explanation pending]",
      subjectName: SubjectName.SOCIAL_STUDIES,
      topicId: "civics",
      subTopicId: "social-justice",
      difficulty: "easy",
    },
];
